import { byChannel, money } from "@lenterne/catalog";
import { Arrow } from "@lenterne/ui";
import type { BrandConfig } from "./brand";

export function HomePage({ brand }: { brand: BrandConfig }) {
  const items = byChannel(brand.channel);
  if (brand.channel === "brindes") return <main id="conteudo" className="gifts-home"><section className="gifts-hero"><div className="shell hero-copy"><p className="eyebrow">Fabricamos em Taboão da Serra</p><h1>{brand.headline}</h1><p>{brand.intro}</p><a className="button button-primary" href="/catalogo">{brand.primaryCta} <Arrow /></a></div><div className="hero-collage" aria-hidden="true"><img src={items[0].image} alt="" /><img src={items[1].image} alt="" /></div></section><section className="occasion shell"><header><p>Do evento para o cotidiano</p><h2>Um produto que continua falando pela sua marca.</h2></header><div className="occasion-list"><span>Eventos corporativos</span><span>Equipes e identificação</span><span>Festas e celebrações</span><span>Campanhas promocionais</span></div></section><section className="featured-products shell"><div className="section-head"><h2>Escolhas para personalizar</h2><a href="/catalogo">Ver catálogo completo <Arrow /></a></div><div className="editorial-grid">{items.slice(0, 3).map((product, index) => <a className={`editorial-product product-${index + 1}`} href={`/produto/${product.slug}`} key={product.id}><figure><img src={product.image} alt={product.imageAlt} /></figure><div><h3>{product.name}</h3><p>A partir de {product.minimumQuantity} unidades · {money(product.price)} por unidade</p></div></a>)}</div></section><section className="process"><div className="shell process-inner"><h2>Você envia a ideia.<br />Nós cuidamos da peça.</h2><ol><li><span>01</span>Escolha o produto e a quantidade.</li><li><span>02</span>Envie sua arte ou peça ajuda.</li><li><span>03</span>Aprove a proposta antes da produção.</li></ol><a className="button button-secondary" href="/orcamento">Começar um orçamento</a></div></section></main>;

  return <main id="conteudo" className="hardware-home"><section className="hardware-hero shell"><div><h1>{brand.headline}</h1></div><div className="hardware-intro"><p>{brand.intro}</p><a className="button button-primary" href="/catalogo">{brand.primaryCta} <Arrow /></a></div></section><section className="spec-strip"><div className="shell"><span>Argolas · 13—22 mm</span><span>Garras · 09—25 mm</span><span>Clips · solto ou montado</span><span>Pacotes para produção</span></div></section><section className="technical-catalog shell"><aside><p className="eyebrow">Linha principal</p><h2>Componentes que chegam prontos para o seu fluxo.</h2><a href="/catalogo">Todos os itens <Arrow /></a></aside><div className="technical-list">{items.map((product) => <a href={`/produto/${product.slug}`} className="technical-row" key={product.id}><img src={product.image} alt={product.imageAlt} /><div><span>{product.category}</span><h3>{product.name}</h3></div><dl>{Object.entries(product.specs).slice(0, 2).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><strong>{money(product.price)}<small>/un.</small></strong><Arrow /></a>)}</div></section><section className="manufacturing"><div className="shell"><p className="eyebrow">Somos fabricantes</p><h2>Preço, lote e atendimento conversados com quem conhece a produção.</h2><a className="button button-secondary" href="/orcamento">Falar sobre meu pedido</a></div></section></main>;
}
